---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease #Custom Object type for use with Flux Helm Operator
metadata:
  name: consul #Name of the object
  namespace: default #Namespace in which to install the Chart
  annotations:
    flux.weave.works/automated: "true" #Set this to true to automate installation/updating of this release when the Chart of this object changes
spec:
  releaseName: consul #Name of the Helm release

  ########################################################################
  # Values section defines the location of the chart
  # This example pulls the chart from a Git repository
  ########################################################################
  chart:
    git: https://github.com/hashicorp/consul-helm #Repository where the pull the chart from
    ref: master #Branch or tag to retreive the chart from

  ########################################################################
  # Values section defines the parameters to the chart
  # These are specific to the chart being installed
  ########################################################################
  values:
    # Choose an optional name for the datacenter
    global:
      datacenter: minikube

    # Enable the Consul Web UI via a NodePort
    ui:
      service:
        type: 'NodePort'

    server:
      replicas: 1
      bootstrapExpect: 1
      disruptionBudget:
        enabled: true
        maxUnavailable: 0
